### ISSUE TITLE
OnChange Formula showing Error

### ISSUE THREAD

**Issue by anubhav247** [ritikaagarwal08/Screenshot#7]
Hey Ritika,

I went your blog site and it mentions that the OnChange property of this control should be set to `ClearCollect(ImageCollection,{Name: "CapturedScreen.jpg", ContentBytes: 'btd_btd.screenshot(00000001-0000-0000-0001-00000000009b)1'.OutPut, '@odata.type':""});` but it seems powerapps studio is not accepting it.

![image](https://user-images.githubusercontent.com/54588046/111737089-f9afe380-88a4-11eb-9f14-2bc8b54af695.png)

Hope i am not doing something wrong.

Regards,
Anubhav

**Comment by anubhav247** [comment]
My bad....Forgot to change the control name.. Thanks

**Comment by AbhijeetT17** [comment]
Hi can you please share some details ? I am facing the same issue
